### ISSUE TITLE
Panel emty

### ISSUE THREAD

**Issue by riesi77** [fredck/ha-data-editor#1]
Hi,
thanks for contributing such a (hopefulle) usefull tool.
I have installed ha-data-editor the first time today, using HACS. Restart done, the entry for the panel appears on the right side. However, the UI is empty.

![image](https://github.com/fredck/ha-data-editor/assets/67387975/6072f170-0350-40c3-a929-8147d617e8c6)

**Comment by fredck** [comment]
Yes... there is this effect... you have to refresh the browser, probably.  
  
I need to update the documentation for that. Thanks!

**Comment by fredck** [comment]
Add the note to README with 8eb14f9
